### ISSUE TITLE
Needs web login for authetication token

### ISSUE THREAD

**Issue by SlovenlyTF** [Educado-App/educado-backend#16]
We need an authentication token to access the different courses on web-frontend.

(edit)
We need any kind of token or an admin user token that have acces to all course. Most of our PBI's depend on having a token, they are:
[Web Create] As a content creator, I want to be able to put information on the new section of the new course I'm creating
[Web Create] As a content creator, I want to be able to add a section on the new course I'm creating
[Web Create] As a content creator, I want to be able to put a lecture on the section I'm creating
[Web Create] As a content creator, I want to be able to put an exercise on the section I'm creating

**Comment by MGLarsenSW** [comment]
A token is provided on login. Token is stored in local storage. Signout removes the token and logging back ind creates a new token. Functionallity is under onboarding-login_signup both, same branch name on backend and frontend

**Comment by SlovenlyTF** [comment]
We unfortunately have to reopen the issue. The login seems great and working, but the token isn't handled correctly.
The backend doesn't save the token, and the front end receives the token but is overwritten by a NULL token from the backend.
I have put the files that seem to overwrite the frontend token below, and possibly what tries to handle the token backend as well.

Frontend: app/src/contexts --> useAuthStore.ts
Backend: auth --> authHandler.js

Hope we can figure something out :D

**Comment by Adachigaming** [comment]
So, just to make it clear: upon accessing the Courses route, which I presume you've fixed, the token is set to null?

**Comment by SlovenlyTF** [comment]
Yes, that is correct. However, we have found a temporary solution with a "dummy" token. Though, we still need the correct token for the final merge.

**Comment by Adachigaming** [comment]
The issue was a result of interplay between old and new code. As you also figured out, the "courses" page would call a function to NULL the token, as it couldn't find the specific token it needed. I have removed it, and made sure that upon accessing the /courses route, that the token remains.
Did you also need a fix on the backend? The file you provided above related to the handling of the mobile users, but if you need the contentCreator token to be saved, I can probably also fix that, provided you guys know what to do with it after XD

**Comment by magnemo** [comment]
done
